web/router.ex
defmodule Tessera.Router do
  use Tessera.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Tessera.Auth, repo: Tessera.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Tessera do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/logout", SessionController, :delete
    get "/login", SessionController, :new
    get "/signup", UserController, :new

    resources "/users", UserController
    resources "/tickets", TicketController 
    resources "/projects", ProjectController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Tessera do
  #   pipe_through :api
  # end
end

web/controllers/session_controller.ex
defmodule Tessera.SessionController do
  use Tessera.Web, :controller

  plug :put_layout, "login_signup_layout.html"

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, 
   %{"session" => %{ "username" => username, "password" => password}}) do
    case Tessera.Auth.login_by_username_and_pass(conn, username, password, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Successfully logged in.")
        |> redirect(to: "/")
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Wrong username or password.")
        |> render("new.html")
    end
   end

   def delete(conn, _opts) do
     conn
     |> Tessera.Auth.logout
     |> put_flash(:info, "Successfully logged out.")
     |> redirect(to: page_path(conn, :index))
   end
end

web/views/session_view.ex
defmodule Tessera.SessionView do
  use Tessera.Web, :view
end

web/templates/session/new.html.eex
<div class="big-form">
  <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %> 
    <h1 class="text-center">Sign In</h1>
    <div class="form-group">
      <%= text_input f, :username, placeholder: "Username", class: "form-control" %> 
    </div>
    <div class="form-group">
      <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    </div>
    <%= submit "Log in", class: "btn btn-success form-control" %> 
  <% end %>
  <a class="btn btn-block btn-social btn-twitter">
    <span class="fa fa-twitter"></span> Sign in with Twitter
  </a>
  <a class="btn btn-block btn-social btn-github">
    <span class="fa fa-github"></span> Sign in with Github
  </a>
  <a class="btn btn-block btn-social btn-google">
    <span class="fa fa-google"></span> Sign in with Google
  </a>
  <h5>
    New user? Sign up <a href="/signup">here</a>
  </h5>
</div>